version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: groupsguru-postgres
    environment:
      POSTGRES_DB: groupsguru_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gg_prod_sec_2026_!@#
    ports:
      - "5432:5432"
    volumes:
      - groupsguru-postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  groupsguru-postgres-data:
